---
- name: Setup Neovim
  hosts: all
  become: yes
  tasks:
    - name: Install Neovim dependencies
      apt:
        pkg:
          - git
          - make
          - unzip
          - gcc
          - ripgrep
          - xclip
          - neovim
          - nodejs
          - npm
        state: present
        update_cache: yes

    - name: Ensure Neovim config directory exists
      file:
        path: "/home/vagrant/.config/nvim"
        state: directory
        owner: vagrant
        group: vagrant
        mode: '0755'

    - name: Clone kickstart.nvim
      git:
        repo: "https://github.com/nvim-lua/kickstart.nvim.git"
        dest: "/home/vagrant/.config/nvim"
        force: yes
      become_user: vagrant

    - name: Set Neovim as default editor
      blockinfile:
        path: /home/vagrant/.bashrc
        block: |
          export EDITOR=nvim
          export VISUAL=nvim
          alias vim=nvim
        marker: "# {mark} ANSIBLE MANAGED BLOCK - NVIM CONFIG"

    - name: Run initial Neovim setup
      shell: |
        nvim --headless "+Lazy! sync" +qa
      become_user: vagrant
      environment:
        HOME: /home/vagrant

- name: Setup Tmux Config
  hosts: all
  become: yes
  roles:
    - tmux_config
