---
- name: Create PrivEsc directory
  file:
    path: "{{ priv_esc_dir }}"
    state: directory
    mode: '0755'

- name: Clone pentesting tools
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    force: yes
  loop:
    - { repo: 'https://github.com/rebootuser/LinEnum', dest: '{{ priv_esc_dir }}/LinEnum' }
    - { repo: 'https://github.com/mzet-/linux-exploit-suggester', dest: '{{ priv_esc_dir }}/linux-exploit-suggester' }
    - { repo: 'https://github.com/carlospolop/privilege-escalation-awesome-scripts-suite', dest: '{{ priv_esc_dir }}/PEASS-ng' }
    - { repo: 'https://github.com/DominicBreuker/pspy', dest: '{{ priv_esc_dir }}/pspy' }

- name: Download linPEAS shell script
  get_url:
    url: https://github.com/carlospolop/PEASS-ng/releases/latest/download/linpeas.sh
    dest: /opt/linpeas.sh
    mode: '0755'