---
- name: Install required dependencies
  apt:
    pkg:
      - git
      - make
      - unzip
      - gcc
      - ripgrep
      - xclip
    state: present
    update_cache: yes

- name: Download Neovim AppImage using curl
  shell: |
    curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
    chmod +x nvim.appimage
    mv nvim.appimage /usr/local/bin/nvim
  args:
    chdir: /tmp
  register: curl_nvim
  changed_when: curl_nvim.rc == 0

- name: Ensure Neovim config directory exists
  file:
    path: "/home/vagrant/.config/nvim"
    state: directory
    owner: vagrant
    group: vagrant
    mode: '0755'

- name: Clone kickstart.nvim
  git:
    repo: "https://github.com/nvim-lua/kickstart.nvim.git"
    dest: "/home/vagrant/.config/nvim"
    force: yes
  become_user: vagrant

- name: Run Neovim headless to install plugins
  become_user: vagrant
  shell: nvim --headless "+sleep 1" +qa
  args:
    chdir: /home/vagrant
  changed_when: false