- name: Ensure /opt directory exists
  file:
    path: /opt
    state: directory
    mode: '0755'

- name: Copy TryHackMe VPN configuration
  copy:
    src: thm.ovpn
    dest: /opt/thm.ovpn
    mode: '0600'
    owner: root
    group: root
